# This is a basic workflow to help you get started with Actions

name: NuGet Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
      - name: Build and generate NuGet package
        run: dotnet pack -c Release -o out  
      - name: Push generated package to NuGet
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
